[package]
authors = []
name    = "only_caller"
version = "1.0.0"

[addresses]
only_caller = "_"
some_addr   = "_"

[dev-addresses]
only_caller = "0x22222"
some_addr   = "0x44444"

[dependencies.AptosFramework]
git    = "https://github.com/aeryz/aptos-core.git"
rev    = "d34bb3e3dad03241967c0263a6f1fcfe6bccb7d7"
subdir = "aptos-move/framework/aptos-framework"

[dependencies]
# AptosStdlib = { git = "https://github.com/aeryz/aptos-core.git", subdir = "aptos-move/framework/aptos-framework/", rev = "movement" }
another_app = { local = "../test" }


[dev-dependencies]
