[package]
name = "cw20-token-minter"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
license-file.workspace = true
publish.workspace = true
repository.workspace = true

[dependencies]
cosmwasm-std = { version = "1.5" }
cw20 = "1.1.2"
cw20-base = { version = "1.1.2", features = ["library"] }
token-factory-api = { workspace = true }
cosmwasm-schema = { version = "1.5" }
cw-storage-plus   = { version = "1.2" }
serde = { workspace = true, features = [ "derive" ] }
thiserror = { workspace = true}
ucs03-zkgm-msg = { workspace = true }

[lints]
workspace = true
