[package]
authors.workspace      = true
edition.workspace      = true
license-file.workspace = true
name                   = "native-token-minter"
publish.workspace      = true
repository.workspace   = true
version                = "0.0.0"

[dependencies]
cosmwasm-schema             = { version = "1.5" }
cosmwasm-std                = { version = "1.5" }
token-factory-api           = { workspace = true }
ucs03-zkgm-token-minter-api = { workspace = true }

[lints]
workspace = true
