[package]
name = "ucs03-zkgm"
version = "1.0.0"
authors = []

[addresses]
zkgm = "_"

[dev-addresses]
zkgm = "0xbeef"

[dependencies.AptosFramework]
git = "https://github.com/movementlabsxyz/aptos-core.git"
rev = "movement"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]
